### ISSUE TITLE
I2S.h seems missing

### ISSUE THREAD

**Issue by observator-x** [tierneytim/microDecoder#1]
Hi, it seems the I2S library is missing when using the SPI_MP3_I2S.ino example,
or is it an specific external library that can be used with the example?

and can you please give an (small) example of feeding a mp3 packet from a loop into the decoder?
for example just a progmem chunk that is looped and decoded in I2S?

kind regards.

**Comment by tierneytim** [comment]
Good catch, 

I'm working on an ESP32 specific I2S library that can be used with microdecoder to play audio files. I've updated the example and committed the new library (I2S32). Let me know if this works and I'll close the issue.

**Comment by observator-x** [comment]
thanks! works. so the issue could be closed.
